routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/about', function () {
    return view('about');
});
Route::get('/facilities', function () {
    return view('facilities');
});
Route::get('/galery', function () {
    return view('galery');
});
Route::get('/testimony', function () {
    return view('testimony');
});
Route::get('/confirmation/form', function () {
    return view('confirmations._form');
});
Route::post('/search/room', 'BookingsController@searchRoom');
Route::post('/booking/form', 'BookingsController@bookingForm');
Route::post('/booking/process', 'BookingsController@bookingAction');

Auth::routes();
Route::resource('confirmationpayments', 'ConfirmationPaymentsController');

Route::get('/home', 'HomeController@index')->name('home');	
Route::group(['prefix'=>'admin', 'middleware'=>['auth','role:admin']], function () {
	Route::resource('rooms', 'RoomsController');
	Route::resource('users', 'UsersController');
	Route::resource('list_booking', 'ListBookingsController');
	Route::resource('guests', 'GuestsController');
	Route::resource('companies', 'CompaniesController');
	Route::resource('confirmations', 'ConfirmationsController');
	Route::get('settings/change-profile', 'SettingsController@changeProfile');
	Route::post('settings/change-profile', 'SettingsController@changeProfileAct');
	Route::get('settings/change-password', 'SettingsController@editPassword');
	Route::post('settings/change-password', 'SettingsController@updatePassword');
});

resources/views/about.blade.php
@extends('layouts.home')

@section('content')
    

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="{{ url('/') }}">Home</a></li>
                        <li class="active"><a href="{{ url('/about') }}">About</a></li>
                        
                        <li><a href="{{ url('/facilities') }}">Facilities</a></li>
                        <li><a href="{{ url('/galery') }}">Galery</a></li>
                        <li class=""><a href="{{ url('/testimony') }}">Testimony</a></li>
                        <li class=""><a href="{{ url('/confirmation/form') }}">Confirmation</a></li>
                    </ul>
                </div><!-- /.navbar-collapse -->    
                
            </nav>
        </div>
    </div>
    <!-- about -->
    <div class="about">
        <div class="container">
            <div class="about-grids">
                <div class="col-md-6 about-grid animated wow slideInLeft" data-wow-delay=".5s">
                    <h3>About Us</h3>
                    <img src="images/banner2.jpg" alt=" " class="img-responsive" />
                    <h2>Vilaa Jaya Sakti adalah perusahaan yang bergerak di bidang penyewaan villa yang beralamat di Jalan Pelabuhan Rancabuaya Kec. Caringin Kab. Garut.</h2>
                    <p> Villa yang berlokasi didekat pantai ini memiliki 30 kamar yang terdiri dari 2 tipe kamar yaitu tipe yang pertama memiliki fasilitas 1 tempat tidur dan yang kedua memiliki fasilitas 2 tempat tidur.
                    Fasilitas kamar pada Villa Jaya Sakti ini dilengkapi dengan televisi berbayar, AC (Air Conditioner), Water Hater dan perlengkapan mandi yang lengkap. Villa Jaya Sakti ini melayani 24 jam dan tarif yang ditawarkan relatif murah dan bersaing. Lokasi yang strategis dan dekat dengan pantai, serta mempunyai pemandangan yang indah.
</p>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
<!-- //about -->
@endsection

resources/views/facilities.blade.php
@extends('layouts.home')

@section('content')
    

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="{{ url('/') }}">Home</a></li>
                        <li><a href="{{ url('/about') }}">About</a></li>
                        
                        <li class="active"><a href="{{ url('/facilities') }}">Facilities</a></li>
                        <li><a href="{{ url('/galery') }}">Galery</a></li>
                        <li class=""><a href="{{ url('/testimony') }}">Testimony</a></li>
                        <li class=""><a href="{{ url('/confirmation/form') }}">Confirmation</a></li>
                    </ul>
                    
                </div><!-- /.navbar-collapse -->    
                
            </nav>
        </div>
    </div>
    <!-- about -->
    <div class="about">
        <div class="container">
            <div class="about-grids">
                <div class="col-md-6 about-grid animated wow slideInLeft" data-wow-delay=".5s">
                    <h3>Guest Facilities</h3>
                    <div class="about-gd">
                        <div class="about-gd-left">
                            <h4><span class="glyphicon glyphicon-ok-circle"></span></h4>
                        </div>
                        <div class="about-gd-right">
                            <p>Open 24 Hours</p>
                        </div>
                        <div class="clearfix"> </div>
                    </div>
                    <div class="about-gd">
                        <div class="about-gd-left">
                            <h4><span class="glyphicon glyphicon-ok-circle"></span></h4>
                        </div>
                        <div class="about-gd-right">
                            <p>Lobby</p>
                        </div>
                        <div class="clearfix"> </div>
                    </div>
                    <div class="about-gd">
                        <div class="about-gd-left">
                            <h4><span class="glyphicon glyphicon-ok-circle"></span></h4>
                        </div>
                        <div class="about-gd-right">
                            <p>Gazebo</p>
                        </div>
                        <div class="clearfix"> </div>
                    </div>
                    <div class="about-gd">
                        <div class="about-gd-left">
                            <h4><span class="glyphicon glyphicon-ok-circle"></span></h4>
                        </div>
                        <div class="about-gd-right">
                            <p>Complimentary Parking</p>
                        </div>
                        <div class="clearfix"> </div>
                    </div>
                    <div class="about-gd">
                        <div class="about-gd-left">
                            <h4><span class="glyphicon glyphicon-ok-circle"></span></h4>
                        </div>
                        <div class="about-gd-right">
                            <p>Musholla</p>
                        </div>
                        <div class="clearfix"> </div>
                    </div>
                    <div class="about-gd">
                        <div class="about-gd-left">
                            <h4><span class="glyphicon glyphicon-ok-circle"></span></h4>
                        </div>
                        <div class="about-gd-right">
                            <p>Cleaning Service</p>
                        </div>
                        <div class="clearfix"> </div>
                    </div>
                    <div class="about-gd">
                        <div class="about-gd-left">
                            <h4><span class="glyphicon glyphicon-ok-circle"></span></h4>
                        </div>
                        <div class="about-gd-right">
                            <p>Garden</p>
                        </div>
                        <div class="clearfix"> </div>
                    </div>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
<!-- //about -->
@endsection

resources/views/galery.blade.php
@extends('layouts.home')

@section('content')
    

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="{{ url('/') }}">Home</a></li>
                        <li><a href="{{ url('/about') }}">About</a></li>
                        
                        <li><a href="{{ url('/facilities') }}">Facilities</a></li>
                        <li class="active"><a href="{{ url('/galery') }}">Galery</a></li>
                        <li class=""><a href="{{ url('/testimony') }}">Testimony</a></li>
                        <li class=""><a href="{{ url('/confirmation/form') }}">Confirmation</a></li>
                    </ul>
                    
                </div><!-- /.navbar-collapse -->    
                
            </nav>
        </div>
    </div>
    <!-- blog -->
    <div class="blog">
        <div class="container">
            <h2 class="animated wow zoomIn" data-wow-delay=".5s">Galery</h2>
            <div class="blog-grids">
                <div class="col-md-3 blog-grid">
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".5s">
                        <a href="#"><img src="images/1.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".6s">
                        <a href="#"><img src="images/2.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                </div>
                <div class="col-md-3 blog-grid">
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".5s">
                        <a href="#"><img src="images/3.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".6s">
                        <a href="#"><img src="images/4.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                </div>
                <div class="col-md-3 blog-grid">
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".5s">
                        <a href="#"><img src="images/5.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".6s">
                        <a href="#"><img src="images/6.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                </div>
                <div class="col-md-3 blog-grid">
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".5s">
                        <a href="#"><img src="images/7.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".6s">
                        <a href="#"><img src="images/8.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                                                            <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".5s">
                        <a href="#"><img src="images/9.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".6s">
                        <a href="#"><img src="images/10.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                </div>
                <div class="col-md-3 blog-grid">
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".5s">
                        <a href="#"><img src="images/11.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".6s">
                        <a href="#"><img src="images/12.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                </div>
                <div class="col-md-3 blog-grid">
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".5s">
                        <a href="#"><img src="images/13.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".6s">
                        <a href="#"><img src="images/14.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                </div>
                <div class="col-md-3 blog-grid">
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".5s">
                        <a href="#"><img src="images/15.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".6s">
                        <a href="#"><img src="images/16.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                                        <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".5s">
                        <a href="#"><img src="images/17.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".6s">
                        <a href="#"><img src="images/18.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                </div>
                <div class="col-md-3 blog-grid">
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".5s">
                        <a href="#"><img src="images/19.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".6s">
                        <a href="#"><img src="images/20.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                </div>
                <div class="col-md-3 blog-grid">
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".5s">
                        <a href="#"><img src="images/21.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".6s">
                        <a href="#"><img src="images/22.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                </div>
                <div class="col-md-3 blog-grid">
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".5s">
                        <a href="#"><img src="images/23.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".6s">
                        <a href="#"><img src="images/24.jpg" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                </div>
                <div class="clearfix"> </div>
            </div>

        </div>
    </div>
<!-- //blog -->
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
	    <section class="content-header">
	      <h1>
	        Dashboard
	      </h1>
	      <ol class="breadcrumb">
	        <li><a href="{{ url('/home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
	        <li class="active">Dashboard</li>
	      </ol>
	    </section>

	    <!-- Main content -->
	    <section class="content">
	      <div class="col-lg-2 col-md-2 col-xs-2 thumb" align="center">
	                <a class="thumbnail" href="{{ url('/home') }}">
	                    <i class="fa fa-fw fa-dashboard fa-5x"></i>
	                    <h4>Dashboard<br><br></h4>
	                </a>
	            </div>
	            <div class="col-lg-2 col-md-2 col-xs-2 thumb" align="center">
	                <a class="thumbnail" href="{{ route('users.index') }}">
	                    <i class="fa fa-fw fa-user fa-5x"></i>
	                    <h4>Profile<br><br></h4>
	                </a>
	            </div>
	            <div class="col-lg-2 col-md-2 col-xs-2 thumb" align="center">
	                <a class="thumbnail" href="{{ route('rooms.index') }}">
	                    <i class="fa fa-fw fa-columns fa-5x"></i>
	                    <h4>Room<br><br></h4>
	                </a>
	            </div>
	            <div class="col-lg-2 col-md-2 col-xs-2 thumb" align="center">
	                <a class="thumbnail" href="{{ route('list_booking.index') }}">
	                    <i class="fa fa-fw fa-book fa-5x"></i>
	                    <h4>Booking<br><br></h4>
	                </a>
	            </div>
	            <div class="col-lg-2 col-md-2 col-xs-2 thumb" align="center">
	                <a class="thumbnail" href="{{ route('guests.index') }}">
	                    <i class="fa fa-fw fa-users fa-5x"></i>
	                    <h4>Guest<br><br></h4>
	                </a>
	            </div>
	            <div class="col-lg-2 col-md-2 col-xs-2 thumb" align="center">
	                <a class="thumbnail" href="{{ route('confirmations.index') }}">
	                    <i class="fa fa-fw fa-phone fa-5x"></i>
	                    <h4>Confirmation<br><br></h4>
	                </a>
	            </div>
	            <div class="col-lg-2 col-md-2 col-xs-2 thumb" align="center">
	                <a class="thumbnail" href="{{ route('logout') }}" onclick="event.preventDefault();
	                                                     document.getElementById('logout-form').submit();">
	                    <i class="fa fa-fw fa-power-off fa-5x"></i>
	                    <h4>Logout<br><br></h4>
	                </a>
	            </div>
	    </section>
	    <!-- /.content -->
	  </div>
	  <!-- /.content-wrapper -->

@endsection

resources/views/testimony.blade.php
@extends('layouts.home')

@section('content')
    

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="{{ url('/') }}">Home</a></li>
                        <li><a href="{{ url('/about') }}">About</a></li>
                        <li><a href="{{ url('/facilities') }}">Facilities</a></li>
                        <li class=""><a href="{{ url('/galery') }}">Galery</a></li>
                        <li class="active"><a href="{{ url('/testimony') }}">Testimony</a></li>
                        <li class=""><a href="{{ url('/confirmation/form') }}">Confirmation</a></li>
                    </ul>
                    
                </div><!-- /.navbar-collapse -->    
                
            </nav>
        </div>
    </div>
    <!-- blog -->
    <div class="blog">
        <div class="container">
            <h2 class="animated wow zoomIn" data-wow-delay=".5s">Testimony</h2>
            <div class="blog-grids">
                <div class="col-md-3 blog-grid">
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".5s">
                        <a href="#"><img src="images/a.png" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".6s">
                        <a href="#"><img src="images/b.png" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                </div>
                <div class="col-md-3 blog-grid">
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".5s">
                        <a href="#"><img src="images/c.png" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".6s">
                        <a href="#"><img src="images/d.png" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                </div>
                <div class="col-md-3 blog-grid">
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".5s">
                        <a href="#"><img src="images/c.png" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                    </div>
                    <div class="blog-grid1 animated wow slideInUp" data-wow-delay=".6s">
                        <a href="#"><img src="images/d.png" alt=" " class="img-responsive" /></a>
                        <div class="blog-grid1-info">
                        </div>
                    </div>
                </div>
                <div class="col-md-3 blog-grid">
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
<!-- //blog -->
@endsection