routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/about', function () {
    return view('about');
});
Route::get('/facilities', function () {
    return view('facilities');
});
Route::get('/galery', function () {
    return view('galery');
});
Route::get('/testimony', function () {
    return view('testimony');
});
Route::get('/confirmation/form', function () {
    return view('confirmations._form');
});
Route::post('/search/room', 'BookingsController@searchRoom');
Route::post('/booking/form', 'BookingsController@bookingForm');
Route::post('/booking/process', 'BookingsController@bookingAction');

Auth::routes();
Route::resource('confirmationpayments', 'ConfirmationPaymentsController');

Route::get('/home', 'HomeController@index')->name('home');	
Route::group(['prefix'=>'admin', 'middleware'=>['auth','role:admin']], function () {
	Route::resource('rooms', 'RoomsController');
	Route::resource('users', 'UsersController');
	Route::resource('list_booking', 'ListBookingsController');
	Route::resource('guests', 'GuestsController');
	Route::resource('companies', 'CompaniesController');
	Route::resource('confirmations', 'ConfirmationsController');
	Route::get('settings/change-profile', 'SettingsController@changeProfile');
	Route::post('settings/change-profile', 'SettingsController@changeProfileAct');
	Route::get('settings/change-password', 'SettingsController@editPassword');
	Route::post('settings/change-password', 'SettingsController@updatePassword');
});

app/Booking.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Booking extends Model
{
    //
    protected $table='bookings';

    public function room(){
        return $this->belongsTo('App\Room');
    }

    public function prices(){
        return $this->belongsTo('App\Price');
    }

    public function customer(){
        return $this->belongsTo('App\Customer');
    }

    public function confirmation(){
        return $this->hasOne('App\Confirmation');
    }

    public function checkin(){
        return $this->hasOne('App\Checkin');
    }

    public function checkout(){
        return $this->hasOne('App\Checkout');
    }

}

app/Http/Controllers/BookingsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
use App\Booking;
use App\Room;
use App\Customer;
use App\Price;
use PDF;
use Carbon\Carbon;
use Illuminate\Mail\Mailable;
use Illuminate\Support\Facades\Mail;
use Illuminate\Notifications\Messages\MailMessage;
use App\Mail\Emailconfirmation;

class BookingsController extends Controller
{
    //
    function searchRoom(Request $request){
    	$check_in = $request->check_in;
		$check_out = $request->check_out;
		$capacity = $request->number;

        $check_ins = date('Y-m-d', strtotime($check_in));
        $check_outes = date('Y-m-d', strtotime($check_out));

		$search_room = Room::with('booking')/*where('check_in', '=', $check_in)
			->where('check_out', '<=', $check_out)*/
            ->where('capacity', '=', $capacity)
            // ->whereNotBetween('booking.check_in', [$check_ins, $check_outes])
            ->whereHas("booking", function ($query) use ($check_ins, $check_outes) {
				// $query->whereRaw("check_in <= '$check_in' && check_out >= '$check_out' ");
                // $query->whereNotBetween('check_in', [$check_ins, $check_outes]);
                // $query->WhereNotBetween('check_out', [$check_ins, $check_outes]);
				// $query->Where('check_in', '=', '');
                $query->whereRaw("check_in NOT BETWEEN '$check_ins' AND '$check_outes'");
				$query->whereRaw("check_out NOT BETWEEN '$check_ins' AND '$check_outes'");
                $query->orWhereRaw("check_in != $check_ins && check_in != $check_outes");
                $query->orWhereRaw("check_out != $check_ins && check_out != $check_outes");

            })
            /*->whereHas("room",function($q) use($capacity){
                    $q->whereRaw("capacity <= '$capacity'");
                    #$q->orwhere('tgl_booking','>=','$hari');
            })*/
            ->get();
            // dd($search_room);exit();

        /*$loop = [];
        foreach ($search_room as $search_room) {
        	# code...
        	$loop[] = $search_room->room_id;
        }
        $search_room = Booking::with('room')->whereNotIn('id',$loop)->get();*/
        /*dd($search_room);exit();*/
        return view('bookings.search-room',compact('search_room','check_in','check_out'));
    }

    function bookingForm(Request $request){
		$room_id = $request->room_id;
    	$check_in = $request->check_in;
		$check_out = $request->check_out;
		/*dd($room_id);exit();*/
        return view('bookings.form-booking',compact('room_id','check_in','check_out'));
    }

    function bookingAction(Request $request){
		$this->validate($request, [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:50',
            'no_rek' => 'required|max:20',
            'no_rek' => 'required|max:20',
            'bank' => 'required',
            'atas_nama' => 'required',
        ]);

        $room_id = $request->room_id;
        $check_in = $request->check_in;
        $check_out = $request->check_out;
        $name = $request->name;
        $email = $request->email;
        $phone_number = $request->phone_number;

        $konversi_check_in = new Carbon($check_in);
        $konversi_check_out = new Carbon($check_out);
        $lama = $konversi_check_in->diffInDays($konversi_check_out);
		
		$customer = new Customer;
        $customer->name = $request->name;
        $customer->email = $request->email;
        $customer->phone_number = $request->phone_number;
        $customer->no_rek = $request->no_rek;
        $customer->bank = $request->bank;
        $customer->save();
		
		$booking = new Booking;
        $booking->room_id = $request->room_id;
        $booking->price_id = $request->room_id;
        $booking->check_in = $request->check_in;
        $booking->check_out = $request->check_out;
        $booking->status = "Belum Transfer";
        $booking->customer_id=$customer->id;
        $booking->save();

        $no_trans =$booking->id;

        $room = Room::select('room')->where('id',$room_id)->value('room');
        $price = Price::select('price')->where('room_id',$room_id)->value('price');
        $total = $price * $lama ;

        $booking = $this;
        Mail::send('bookings.send-email', compact('room','no_trans','check_in','check_out','name','email','phone_number','lama','price','total','room_id'), function ($m) use ($request) {
            $m->to($request->email)->subject('Silahkan melakukan transfer pembayaran');
        });
        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Terima kasih, silahkan Cek email anda untuk melakukan transfer Pembayaran & konfirmasi pembayaran"
        ]);
        return redirect('/');

		/*dd($room_id);exit();*/
        /*return view('bookings.form-booking',compact('room_id','check_in','check_out'));*/
    }
}

resources/views/bookings/_form.blade.php
<h5>Check In</h5>
<div class="book_date">
        <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
        <input class="" id="" type="date" name="check_in" required="required">
</div>  
<h5>Check Out</h5>
 <div class="book_date">
        <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
        <input class="" id="" type="date" name="check_out" required="required">
</div>
 <h5>Guests</h5>
 
 <div class="section_room">
      <select name="number" class="frm-field required sect" required="required">
            <option value="">--Select--</option>
            <option value="1">1</option>
            <option value="2">2</option> 
            <option value="3">3</option>                 
            <option value="4">4</option>                              
      </select>
 </div> 
<div class="book">
        <input type="submit" value="Make Your Booking">
</div>

resources/views/bookings/form-booking.blade.php
@extends('layouts.home')

@section('content')
    

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="{{ url('/') }}">Home</a></li>
                        <li><a href="{{ url('/about') }}">About</a></li>
                        
                        <li><a href="{{ url('/facilities') }}">Facilities</a></li>
                        <li class=""><a href="{{ url('/galery') }}">Galery</a></li>
                        <li class="active"><a href="{{ url('/testimony') }}">Testimony</a></li>
                        <li class="active"><a href="{{ url('/confirmation/form') }}">Confirmation</a></li>
                    </ul>
                    
                    <div class="search">
                        <form>
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span><input type="email" class="text" value="Enter Your Text..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter Your Text...';}" required="">
                        </form>
                    </div>
                </div><!-- /.navbar-collapse -->    
                
            </nav>
        </div>
    </div>
    <!-- blog -->
    <div class="blog">
        <div class="container">
            <h2 class="animated wow zoomIn" data-wow-delay=".5s">Form Booking</h2>
            <div class="blog-grids">
                {!! Form::open(['url' => url('/booking/process'), 'method' => 'post', 'files'=>'true', 'class'=>'form-horizontal']) !!}
					<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
						{!! Form::label('name', 'Nama', ['class'=>'col-md-2 control-label']) !!}
						<div class="col-md-4">
							{!! Form::text('name', null, ['class'=>'form-control']) !!}
							{!! $errors->first('name', '<p class="help-block">:message</p>') !!}
						</div>
					</div>

					<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
						{!! Form::label('email', 'Email', ['class'=>'col-md-2 control-label']) !!}
						<div class="col-md-4">
							{!! Form::email('email', null, ['class'=>'form-control']) !!}
							{!! $errors->first('email', '<p class="help-block">:message</p>') !!}
						</div>
					</div>

					<div class="form-group{{ $errors->has('phone_number') ? ' has-error' : '' }}">
						{!! Form::label('phone_number', 'No. Telp/HP', ['class'=>'col-md-2 control-label']) !!}
						<div class="col-md-4">
							{!! Form::text('phone_number', null, ['class'=>'form-control']) !!}
							{!! $errors->first('phone_number', '<p class="help-block">:message</p>') !!}
						</div>
					</div>

					<div class="form-group{{ $errors->has('no_rek') ? ' has-error' : '' }}">
						{!! Form::label('no_rek', 'No Rekening', ['class'=>'col-md-2 control-label']) !!}
						<div class="col-md-4">
							{!! Form::text('no_rek', null, ['class'=>'form-control']) !!}
							{!! $errors->first('no_rek', '<p class="help-block">:message</p>') !!}
						</div>
					</div>

					<div class="form-group{{ $errors->has('bank') ? ' has-error' : '' }}">
						{!! Form::label('bank', 'Bank', ['class'=>'col-md-2 control-label']) !!}
						<div class="col-md-4">
							<select name="bank" class="form-control">
								<option value="">--Pilih--</option>
								<option value="BCA">BCA</option>
								<option value="BNI">BNI</option>
								<option value="BRI">BRI</option>
								<option value="Danamon">Danamon</option>
								<option value="Mandiri">Mandiri</option>
							</select>
							{!! $errors->first('bank', '<p class="help-block">:message</p>') !!}
						</div>
					</div>

					<div class="form-group{{ $errors->has('atas_nama') ? ' has-error' : '' }}">
						{!! Form::label('atas_nama', 'Atas Nama', ['class'=>'col-md-2 control-label']) !!}
						<div class="col-md-4">
							{!! Form::text('atas_nama', null, ['class'=>'form-control']) !!}
							{!! $errors->first('atas_nama', '<p class="help-block">:message</p>') !!}
						</div>
					</div>

					<input type="text" name="room_id" value="{{ $room_id }}" hidden="hidden">
                                    <input type="date" name="check_in" value="{{ $check_in }}" hidden="hidden">
                                    <input type="date" name="check_out" value="{{ $check_out }}" hidden="hidden">
					<div class="form-group">
						<div class="col-md-2 col-md-offset-2">
							<button type="submit" class="btn btn-primary">
								<i class="fa fa-btn fa-file"></i> Booking
							</button>
						</div>
					</div>
				{!! Form::close() !!}
            </div>
        </div>
    </div>
<!-- //blog -->
@endsection

resources/views/bookings/index.blade.php
@extends('layouts.app')
@section('content')
	<!-- Content Header (Page header) -->
	    <section class="content-header">
	      <h1>
	        Booking
	      </h1>
	      <ol class="breadcrumb">
	        <li><a href="{{ route('confirmations.index') }}"><i class="fa fa-book"></i> Booking</a></li>
	        <li class="active">Index</li>
	      </ol>
	    </section>

	    <!-- Main content -->
	    <section class="content">
	      	<div class="panel panel-warning">
				<div class="panel-heading">
					<h2 class="panel-title">List Of Booking</h2>
				</div>
				<div class="panel-body">
					{!! $html->table(['class'=>'table table-striped table-bordered table-hover']) !!}
				</div>
			</div>
	    </section>
	    <!-- /.content -->
	  </div>
	  <!-- /.content-wrapper -->
@endsection

@section('scripts')
	{!! $html->scripts() !!}
@endsection

resources/views/bookings/search-room.blade.php
@extends('layouts.home')

@section('content')
    

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="{{ url('/') }}">Home</a></li>
                        <li><a href="{{ url('/about') }}">About</a></li>
                        
                        <li><a href="{{ url('/facilities') }}">Facilities</a></li>
                        <li class=""><a href="{{ url('/galery') }}">Galery</a></li>
                        <li class=""><a href="{{ url('/testimony') }}">Testimony</a></li>
                        <li class=""><a href="{{ url('/confirmation/form') }}">Confirmation</a></li>
                    </ul>
                    
                    <div class="search">
                        <form>
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span><input type="email" class="text" value="Enter Your Text..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter Your Text...';}" required="">
                        </form>
                    </div>
                </div><!-- /.navbar-collapse -->    
                
            </nav>
        </div>
    </div>
    <!-- blog -->
    <div class="blog">
        <div class="container">
            <h2 class="animated wow zoomIn" data-wow-delay=".5s">Searching Room...</h2>
            <div class="blog-grids">
                <Table class="table table-striped table-hover table-bordered">
                    <tr>
                        <th width="">Room</th>
                        <th width="">Capacity</th>
                        <th width="65%">Service</th>
                        <th>Price</th>
                        <th>Action</th>
                    </tr>
                    @foreach($search_room as $search)
                        <tr>
                            <td>{{ $search->room }}</td>
                            <td>{{ $search->capacity }}</td>
                            <td>{{ $search->service }}</td>
                            <td>{{ $search->prices->price }}</td>
                            <td align="center">
                                {!! Form::open(['url' => url('/booking/form'), 'method' => 'post', 'class'=>'form-horizontal']) !!}
                                    <input type="text" name="room_id" value="{{ $search->id }}" hidden="hidden">
                                    <input type="date" name="check_in" value="{{ $check_in }}" hidden="hidden">
                                    <input type="date" name="check_out" value="{{ $check_out }}" hidden="hidden">
                                    <input type="submit" value="Booking" class="btn btn-success">
                                {!! Form::close() !!}
                            </td>
                        </tr>
                    @endforeach
                </Table>
            </div>
            
        </div>
    </div>
<!-- //blog -->
@endsection

resources/views/bookings/send-email.blade.php
<!DOCTYPE html>
<html>
<head>
<title>Struk Parkir Online</title>
	<style>
		/* --------------------------------------------------------------
		Hartija Css Print Framework
		* Version: 1.0
		-------------------------------------------------------------- */
		body {
			width:100% !important;
			margin:0 !important;
			padding:0 !important;
			line-height: 1.45;
			font-family: Garamond,"Times New Roman", serif;
			color: #000;
			background: none;
			font-size: 11pt; 
		}
		pre {-moz-tab-size: 16;} /* Code for Firefox */
		pre {-o-tab-size: 16;} /* Code for Opera 10.6-12.1 */
		pre {tab-size: 16;}
		/* Headings */
		h1,h2,h3,h4,h5,h6 { 
			page-break-after:avoid; 
		}
		h1{
			font-size:19pt;
		}
		h2{
			font-size:17pt;
		}
		h3{
			font-size:15pt;
		}
		h4,h5,h6{
			font-size:14pt;
		}
		p, h2, h3 { 
			orphans: 3; widows: 3; 
		}
		code { 
			font: 12pt Courier, monospace; 
		}
		blockquote { 
			margin: 1.2em; padding: 1em; font-size: 12pt; 
		}
		hr { 
			background-color: #ccc;
		}
		/* Images */
		img { 
			float: left; margin: 1em 1.5em 1.5em 0; max-width: 100% !important; 
		}
		a img { 
			border: none; 
		}
		/* Links */
		a:link, a:visited { background: transparent; font-weight: 700; text-decoration: underline;col\
			or:#333; 
		}
		a:link[href^="http://"]:after, a[href^="http://"]:visited:after { content: " (" attr(href) ")\
		"; font-size: 90%; }
		abbr[title]:after { content: " (" attr(title) ")"; }
		/* Don't show linked images */
		a[href^="http://"] {color:#000; }
		a[href$=".jpg"]:after, a[href$=".jpeg"]:after, a[href$=".gif"]:after, a[href$=".png"]:after {\
		content: " (" attr(href) ") "; display:none; }
		/* Don't show links that are fragment identifiers, or use the `javascript:` pseudo protocol .\
		. taken from html5boilerplate */
		a[href^="#"]:after, a[href^="javascript:"]:after {content: "";}
		/* Table */
		table { margin: 1px; text-align:left; }
		th { border-bottom: 1px solid #333; font-weight: bold; }
		td { border-bottom: 1px solid #333; }
		th,td { padding: 4px 10px 4px 0; }
		tfoot { font-style: italic; }
		caption { background: #fff; margin-bottom:2em; text-align:left; }
		thead {display: table-header-group;}
		img,tr {page-break-inside: avoid;}
		/* Hide various parts from the site
		#header, #footer, #navigation, #rightSideBar, #leftSideBar
		{display:none;}
		*/
	</style>
</head>
<body>
	<center>
			<strong>Viila Jaya Sakti</strong><br>
			Jl. Pelabuhan, Rancabuaya Kec Caringin - Garut <br>
			www.villa-jaya-sakti.com<br>
			phone : 63748362, WA : 08564736348<br>
	</center>
	<hr>
	<table>
		<tr>
			<td>
			<pre>
	No. Transaksi 	: {{ $no_trans }}						
	Nama 		: {{ $name }}								
			</pre>
			</td>
			<td>
	<pre>
Tanggal Booking	: {{ date('d-m-Y', strtotime($check_in)) }}
Tanggal Keluar 	: {{ date('d-m-Y', strtotime($check_out)) }}
	</pre>
			</td>
		</tr>
		<tr>
			<td>
			<pre>
	Kode Ruangan		: {{ $room_id }}<br>
	Harga 			: Rp.{{ number_format($price,2) }} /hari<br>
	Lama Parkir 		: {{ $lama }} Hari<br>
	Total Harga		: Rp.{{ number_format($total,2) }}
			</pre>
			</td>
			<td>

			</td>
		</tr>
		<tr>
			<td colspan="2" align="center">
				<strong>
					Silahkan Melakukan Transfer ke No. Rek berikut, Selanjutnya upload bukti transfer tersebut
				</strong>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<pre>
	No. Rek 			Atas Nama 			Nama Bank
				</pre>
			</td>
		</tr>
		<tr>
			<td>
			<pre>
				
	8574849494 			Villa Jaya Sakti 			BCA<br>
	8574841994 			Villa Jaya Sakti 			BNI<br>
	8574842094 			Villa Jaya Sakti 			BNI<br>
	8574847894 			Villa Jaya Sakti 			Danamon<br>
	8574842594 			Villa Jaya Sakti 			Mandiri<br>
				
			</pre>	
			</td>
			<td>
			
			</td>
		</tr>
	</table>
	<center>
	<h6>
		Terima Kasih
	
	</center>
	Hormat Kami,<br><br><br>


	Villa Jaya Sakti<br><br><br>

	Note : Bila reservasi kamar dibatalkan maka uang yang dikembalikan ke pada customer 50 % dari transfer yang dilakaukan customer
</body>
</html>

resources/views/bookings/show.blade.php
@extends('layouts.app')
@section('content')
	    <!-- Content Header (Page header) -->
	    <section class="content-header">
	      <h1>
	        Form Booking
	      </h1>
	      <ol class="breadcrumb">
	        <li><a href="{{ route('rooms.index') }}"><i class="fa fa-book"></i> Booking</a></li>
	        <li class="active">Update</li>
	      </ol>
	    </section>

	    <!-- Main content -->
	    <section class="content">
	      	<div class="panel panel-warning">
				<div class="panel-heading">
					<h2 class="panel-title">Update Status Booking</h2>
				</div>
				<div class="panel-body">
					<Table class="table table-striped table-hover table-bordered">
						<tr>
        					<td width="20%">No. Transaction</td>
							<td>{{ $bookings->id }}</td>
    					</tr>
    					<tr>
        					<td width="20%">Customer</td>
							<td>{{ $bookings->customer->name }}</td>
    					</tr>
    					<tr>
        					<td width="20%">Room</td>
							<td>{{ $bookings->room->room }}</td>
    					</tr>
    					<tr>
        					<td width="20%">Capacity</td>
							<td>{{ $bookings->room->capacity }}</td>
    					</tr>
    					<tr>
        					<td width="20%">Check In</td>
							<td>{{ $bookings->check_in }}</td>
    					</tr>
    					<tr>
        					<td width="20%">Check Out</td>
							<td>{{ $bookings->check_out }}</td>
    					</tr>
    					<tr>
        					<td width="20%">Price</td>
							<td>Rp. {{ number_format($bookings->room->prices->price,2) }} /day</td>
    					</tr>
    					<tr>
        					<td width="20%">Length Of Stay</td>
							<td>{{ $lama }} day</td>
    					</tr>
    					<tr>
        					<td width="20%">Total</td>
							<td>Rp. {{ number_format($total,2) }}</td>
    					</tr>
					</Table>
					
					{!! Form::model($bookings, ['url' => route('list_booking.update', $bookings->id),'method' => 'put', 'files'=>'true', 'class'=>'form-horizontal']) !!}
						<div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
							{!! Form::label('status', 'Status', ['class'=>'col-md-2 control-label']) !!}
							<div class="col-md-4">
							<select name="status" class="form-control" required="required">
					            <option value="{{ $bookings->status }}">{{ $bookings->status }}</option>
					            <option value="Belum Transfer">Belum Transfer</option>
					            <option value="Booking">Booking</option>
					            <option value="Check In">Check In</option> 
					            <option value="Check Out">Check Out</option>                                               
					            <option value="Dibatalkan">Dibatalkan</option>                                               
						    </select>
						    {!! $errors->first('status', '<p class="help-block">:message</p>') !!}
						    </div>
						</div>

						<div class="form-group">
							<div class="col-md-2 col-md-offset-2">
								<button type="submit" class="btn btn-primary">
									<i class="fa fa-btn fa-file"></i> Simpan
								</button>
							</div>
						</div>
					{!! Form::close() !!}
				</div>
			</div>
	    </section>
	    <!-- /.content -->
	  </div>
	  <!-- /.content-wrapper -->
@endsection