routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/about', function () {
    return view('about');
});
Route::get('/facilities', function () {
    return view('facilities');
});
Route::get('/galery', function () {
    return view('galery');
});
Route::get('/testimony', function () {
    return view('testimony');
});
Route::get('/confirmation/form', function () {
    return view('confirmations._form');
});
Route::post('/search/room', 'BookingsController@searchRoom');
Route::post('/booking/form', 'BookingsController@bookingForm');
Route::post('/booking/process', 'BookingsController@bookingAction');

Auth::routes();
Route::resource('confirmationpayments', 'ConfirmationPaymentsController');

Route::get('/home', 'HomeController@index')->name('home');	
Route::group(['prefix'=>'admin', 'middleware'=>['auth','role:admin']], function () {
	Route::resource('rooms', 'RoomsController');
	Route::resource('users', 'UsersController');
	Route::resource('list_booking', 'ListBookingsController');
	Route::resource('guests', 'GuestsController');
	Route::resource('companies', 'CompaniesController');
	Route::resource('confirmations', 'ConfirmationsController');
	Route::get('settings/change-profile', 'SettingsController@changeProfile');
	Route::post('settings/change-profile', 'SettingsController@changeProfileAct');
	Route::get('settings/change-password', 'SettingsController@editPassword');
	Route::post('settings/change-password', 'SettingsController@updatePassword');
});

app/Room.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Room extends Model
{
    //
    protected $table='rooms';

    protected $fillable = [
        'room',
        'capacity',
        'service',
    ];
    
    public function prices(){
        return $this->hasOne('App\Price');
    }

    public function booking(){
        return $this->hasMany('App\Booking');
    }
}

app/Http/Controllers/RoomsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use App\Room;
use App\Price;
use Yajra\Datatables\Html\Builder;
use Yajra\Datatables\Datatables;

class RoomsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, Builder $htmlBuilder)
    {
        //
        if ($request->ajax()) {
            $prices = Price::with('room');
            return Datatables::of($prices)
                ->addColumn('action', function($price){
                return view('datatable._action', [
                    'model' => $price,
                    'form_url' => route('rooms.destroy', $price->id),
                    'edit_url' => route('rooms.edit', $price->id),
                    'detail_url' => route('rooms.show', $price->id),
                    'confirm_message' => 'Yakin mau menghapus ' . $price->nama . '?'
            ]);
            })->make(true);
        }
        $html = $htmlBuilder
            ->addColumn(['data' => 'room.room', 'name'=>'room.room', 'title'=>'Room'])
            ->addColumn(['data' => 'room.capacity', 'name'=>'room.capacity', 'title'=>'Capacity'])
            ->addColumn(['data' => 'price', 'name'=>'price', 'title'=>'Price'])
            ->addColumn(['data' => 'action', 'name'=>'action', 'title'=>'Action', 'orderable'=>false, 'searchable'=>false]);
        return view('rooms.index')->with(compact('html'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('rooms.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request, [
            'room' => 'required|string|unique:rooms',
            'capacity' => 'required|max:11',
            'price' => 'required|max:11',
            'service' => 'required',
        ]);

        $room = new Room;
        $room->room = $request->room;
        $room->capacity = $request->capacity;
        $room->service = $request->service;
        $room->save();

        $price = new Price;
        $price->room_id = $room->id;
        $price->price = $request->price;
        $price->save();

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Berhasil menyimpan $room->room"
        ]);
        return redirect()->route('rooms.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $price = Price::with('room')->where('id', $id)->first();
        return view('rooms.show')->with(compact('price'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $price = Price::with('room')->where('id', $id)->first();
        return view('rooms.edit')->with(compact('price'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $Request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        /*$room = Price::findOrFail($id);*/
        $price = Price::with('room')->where('id', $id)->first();
        $this->validate($request, [
            'room' => 'required|string|max:15|unique:rooms,room,'.$price->id,
            'capacity' => 'required|max:11',
            'price' => 'required|max:11',
            'service' => 'required',
        ]);

        $price->price = $request->price;
        $price->save();

        $room = Room::where('id',$id)->first();
        $room->room = $request->room;
        $room->capacity = $request->capacity;;
        $room->service = $request->service;
        $room->save();

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Berhasil Mengubah $request->room"
        ]);
        return redirect()->route('rooms.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $room = Room::findOrFail($id);
        $room->delete();

        $price = Price::where('id', $id);
        $price->delete();

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Ruaangan dihapus"
        ]);
        return redirect()->route('rooms.index');
    }
}

resources/views/rooms/_form.blade.php
<div class="form-group{{ $errors->has('room') ? ' has-error' : '' }}">
	{!! Form::label('room', 'Room', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
		{!! Form::text('room', null, ['class'=>'form-control']) !!}
		{!! $errors->first('room', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group{{ $errors->has('capacity') ? ' has-error' : '' }}">
	{!! Form::label('capacity', 'Capacity', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
		{!! Form::number('capacity', null, ['class'=>'form-control']) !!}
		{!! $errors->first('capacity', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group{{ $errors->has('service') ? ' has-error' : '' }}">
	{!! Form::label('service', 'Service', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
		{!! Form::textarea('service', null, ['class'=>'form-control']) !!}
		{!! $errors->first('service', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group{{ $errors->has('price') ? ' has-error' : '' }}">
	{!! Form::label('price', 'Price', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
		{!! Form::number('price', null, ['class'=>'form-control']) !!}
		{!! $errors->first('price', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group">
	<div class="col-md-2 col-md-offset-2">
		<button type="submit" class="btn btn-primary">
			<i class="fa fa-btn fa-file"></i> Simpan
		</button>
	</div>
</div>

resources/views/rooms/_formedit.blade.php
<div class="form-group{{ $errors->has('room') ? ' has-error' : '' }}">
	{!! Form::label('room', 'Room', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
		{!! Form::text('room', $price->room->room, ['class'=>'form-control']) !!}
		{!! $errors->first('room', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group{{ $errors->has('capacity') ? ' has-error' : '' }}">
	{!! Form::label('capacity', 'Capacity', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
		{!! Form::number('capacity', $price->room->capacity, ['class'=>'form-control']) !!}
		{!! $errors->first('capacity', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group{{ $errors->has('service') ? ' has-error' : '' }}">
	{!! Form::label('service', 'Service', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
		{!! Form::textarea('service', $price->room->service, ['class'=>'form-control']) !!}
		{!! $errors->first('service', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group{{ $errors->has('price') ? ' has-error' : '' }}">
	{!! Form::label('price', 'Price', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
		{!! Form::number('price', $price->price, ['class'=>'form-control']) !!}
		{!! $errors->first('price', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group">
	<div class="col-md-2 col-md-offset-2">
		<button type="submit" class="btn btn-primary">
			<i class="fa fa-btn fa-file"></i> Simpan
		</button>
	</div>
</div>

resources/views/rooms/create.blade.php
@extends('layouts.app')
@section('content')
	    <!-- Content Header (Page header) -->
	    <section class="content-header">
	      <h1>
	        Room
	      </h1>
	      <ol class="breadcrumb">
	        <li><a href="{{ route('rooms.index') }}"><i class="fa fa-columns"></i> Room</a></li>
	        <li class="active">Create</li>
	      </ol>
	    </section>

	    <!-- Main content -->
	    <section class="content">
	      	<div class="panel panel-warning">
				<div class="panel-heading">
					<h2 class="panel-title">Create Data</h2>
				</div>
				<div class="panel-body">
					{!! Form::open(['url' => route('rooms.store'), 'method' => 'post', 'files'=>'true', 'class'=>'form-horizontal']) !!}
						@include('rooms._form')
					{!! Form::close() !!}
				</div>
			</div>
	    </section>
	    <!-- /.content -->
	  </div>
	  <!-- /.content-wrapper -->
@endsection

resources/views/rooms/edit.blade.php
@extends('layouts.app')
@section('content')
	    <!-- Content Header (Page header) -->
	    <section class="content-header">
	      <h1>
	        Room
	      </h1>
	      <ol class="breadcrumb">
	        <li><a href="{{ route('rooms.index') }}"><i class="fa fa-columns"></i> Room</a></li>
	        <li class="active">Update</li>
	      </ol>
	    </section>

	    <!-- Main content -->
	    <section class="content">
	      	<div class="panel panel-warning">
				<div class="panel-heading">
					<h2 class="panel-title">Update Data</h2>
				</div>
				<div class="panel-body">
					{!! Form::model($price, ['url' => route('rooms.update', $price->id),'method' => 'put', 'files'=>'true', 'class'=>'form-horizontal']) !!}
							@include('rooms._formedit')
						{!! Form::close() !!}
				</div>
			</div>
	    </section>
	    <!-- /.content -->
	  </div>
	  <!-- /.content-wrapper -->
@endsection

resources/views/rooms/index.blade.php
@extends('layouts.app')
@section('content')
	<!-- Content Header (Page header) -->
	    <section class="content-header">
	      <h1>
	        Room
	      </h1>
	      <ol class="breadcrumb">
	        <li><a href="{{ route('rooms.index') }}"><i class="fa fa-columns"></i> Room</a></li>
	        <li class="active">Index</li>
	      </ol>
	    </section>

	    <!-- Main content -->
	    <section class="content">
	      	<div class="panel panel-warning">
				<div class="panel-heading">
					<h2 class="panel-title">Data Room</h2>
				</div>
				<div class="panel-body">
					<p> <a class="btn btn-primary" href="{{ url('/admin/rooms/create') }}">Tambah</a></p>
					{!! $html->table(['class'=>'table table-striped table-bordered table-hover']) !!}
				</div>
			</div>
	    </section>
	    <!-- /.content -->
	  </div>
	  <!-- /.content-wrapper -->
@endsection

@section('scripts')
	{!! $html->scripts() !!}
@endsection

resources/views/rooms/show.blade.php
@extends('layouts.app')
@section('content')
	<!-- Content Header (Page header) -->
	    <section class="content-header">
	      <h1>
	        Room
	      </h1>
	      <ol class="breadcrumb">
	        <li><a href="{{ route('rooms.index') }}"><i class="fa fa-columns"></i> Room</a></li>
	        <li class="active">Detail</li>
	      </ol>
	    </section>

	    <!-- Main content -->
	    <section class="content">
	      	<div class="panel panel-warning">
				<div class="panel-heading">
					<h2 class="panel-title">Detail</h2>
				</div>
				<div class="panel-body">
					<Table class="table table-striped table-hover table-bordered">
						<tr>
        					<td width="20%">ID</td>
							<td>{{ $price->id }}</td>
    					</tr>
    					<tr>
        					<td>Room</td>
							<td>{{ $price->room->room }}</td>
    					</tr>
    					<tr>
        					<td>Capacity</td>
							<td>{{ $price->room->capacity }}</td>
    					</tr>
    					<tr>
        					<td>Price</td>
							<td>Rp. {{ number_format($price->price, 2) }}</td>
    					</tr>
    					<tr>
        					<td>Service</td>
							<td>{{ $price->room->service }}</td>
    					</tr>
					</Table>
				</div>
			</div>
	    </section>
	    <!-- /.content -->
	  </div>
	  <!-- /.content-wrapper -->
@endsection